sudo: required
dist: xenial
language: python
python:
  - "2.7"
cache: pip
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"
matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo"
    - env: ROS_DISTRO="melodic"

before_install:
  - sudo sh -c 'echo "yaml https://raw.githubusercontent.com/ct2034/rosdistro/master/rosdep/python.yaml" > /etc/ros/rosdep/sources.list.d/30-docker-py.list'
  - sudo pip install -U rosdep catkin_tools
  - sudo rosdep init
  - rosdep update

install:
  - rosdep install -v --from-paths .
